services:
  postgres:
    image: postgres:latest
    container_name: taskmanagement_postgres
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanagement_backend
    restart: always
    environment:
      DATABASE_URL: postgres://taskuser:taskpassword@postgres:5432/taskdb
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanagement_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
